services:
  backend:
    build:
      context: ./backend_service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - robyrupe
  frontend:
    build:
      context: ./web_service
      dockerfile: Dockerfile
    ports:
      - "1234:3000"
    networks:
      - robyrupe

networks:
  robyrupe:
    driver: bridge
